name: Run Node.js Application

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 실행
      - 백수만
  pull_request:
    branches:
      - main  # main 브랜치에 대한 PR이 열릴 때 실행

jobs:
  run-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get new files
        id: get_new_files
        run: |
          # Get the list of newly added files
          NEW_FILES=$(git diff --name-status HEAD^ HEAD | grep '^A' | awk '{print $2}')
          echo "new_files=${NEW_FILES}" >> $GITHUB_ENV
      

      - name: Set branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # 사용할 Node.js 버전

      - name: Install dependencies
        run: npm install  # 필요한 경우 dependencies 설치

      - name: Run application
        run: node index.js  # Node.js 애플리케이션 실행
        env:
          USER_NAME: ${{ env.BRANCH_NAME }}
          FILE_NAME: ${{ env.new_files }}
