name: Run Node.js Application

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 실행
      - 백수만
      - 김은호
  pull_request:
    branches:
      - main  # main 브랜치에 대한 PR이 열릴 때 실행

jobs:
  run-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 모든 커밋 기록을 가져옵니다.

      - name: Get new files
        id: get_new_files
        run: |
          # Get the hash of the previous commit
          PREVIOUS_COMMIT=$(git rev-parse HEAD^)
          
          # Get the list of newly added files
          NEW_FILES=$(git diff --name-status $PREVIOUS_COMMIT HEAD | grep '^A' | awk '{print $2}' | tr '\n' ',')
          
          # Check if any new files were found
          if [ -z "$NEW_FILES" ]; then
            echo "new_files=" >> $GITHUB_ENV
          else
            echo "new_files=${NEW_FILES}" >> $GITHUB_ENV
          fi
    
      

      - name: Set branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # 사용할 Node.js 버전

      - name: Install dependencies
        run: npm install  # 필요한 경우 dependencies 설치

      - name: Run application
        run: node index.js  # Node.js 애플리케이션 실행
        env:
          USER_NAME: ${{ env.BRANCH_NAME }}
          FILE_NAME: ${{ env.new_files }}
